# Generated by Django 5.1.3 on 2024-11-14 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=30, null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cedula', models.CharField(max_length=10, primary_key=10, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('contratador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hacienda.contratador')),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hacienda.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='contratador',
            name='Empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hacienda.empleado'),
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Hacienda.empleado')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hacienda.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hacienda.puesto')),
            ],
        ),
    ]
